import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/shadcn-space/blocks/hero-01/header";
import { navigationData } from "@/data/db";
import Footer from "@/components/layouts/Footer";
import { Skiper89 } from "@/components/ui/skiper-ui/skiper89";
import { ThemeProvider } from "@/providers/ThemeProvider";
import HeadAdsServer from "@/components/layouts/HeadAds/HeadAdsServer";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <HeadAdsServer />
          <Header navigationData={navigationData} />
          {children}
          <Skiper89 />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
